### PR TITLE
exfat/fat32 command to bxfat/bat32 (:shrek:)

### PR DESCRIPTION
**Pull request by DanielC7205**
Add meme version of exfat command

### CODE REVIEW

**Comment by cathery** [comment]
Yeah, this is epic.

**Comment by lucyyyyyyy** [comment]
no

**Comment by hax4dazy** [comment]
> no

Yes

**Comment by DanielC7205** [comment]
Please allow the memeing of the exfat command, for Komet's sake of course 😉

**Comment by DanielC7205** [comment]
#22 not as good as bsfat and bxfat

**Comment by lucyyyyyyy** [comment]
> #22 not as good as bsfat and bxfat

wrong

**Comment by DanielC7205** [comment]
> 
> 
> > #22 not as good as bsfat and bxfat
> 
> wrong

right

**Comment by nicholemattera** [comment]
I would like to make these commands use the list cog just like `.es`. These meme commands should also be changed over to us the list cog.

**Pull request closed without merging**
