### PR TITLE
add owoify text meme command 

### PR DESCRIPTION
**Pull request by AnxietyWump**
:smugpepe: ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by hax4dazy** [comment]
You probs should add an admin only thing tbh

**Comment by DanielC7205** [comment]
Yeah

**Comment by DanielC7205** [comment]
I agree with @hax4dazy

**Comment by hax4dazy** [comment]
I agree with @TechGeekGamer

**Comment by DanielC7205** [comment]
~~just add something to allow us to always use it~~

**Comment by AnxietyWump** [comment]
i'm going to kill all of you fools._i don't know how to edit a pull request_

**Comment by DanielC7205** [comment]
Edit it on your fork

**Comment by AnxietyWump** [comment]
and then what??

**Comment by DanielC7205** [comment]
You edit it :shrek:

**Comment by nicholemattera** [comment]
It's fine to be open to everybody like spongebob. Just needs one small change.

**Comment by AnxietyWump** [comment]
do whatever is needed. kek

**Comment by DanielC7205** [comment]
Hey @NicholeMattera!

**Comment by DanielC7205** [comment]
(oh no I turned this into a chatroom)

**Pull request merged**
